### ISSUE TITLE
Duplicate dependency compilation error when trying to install core and websockets

### ISSUE THREAD

**Issue by whoyawn** [Tinder/Scarlet#96]
```
    implementation 'com.tinder.scarlet:scarlet:0.1.9'
    implementation "com.tinder.scarlet:scarlet-websocket-okhttp:0.1.9"
```

gives me

```
Duplicate class com.tinder.scarlet.Deserialization found in modules scarlet-core-0.1.9.jar (com.github.tinder.scarlet:scarlet-core:0.1.9) and scarlet-core-0.1.9.jar (com.tinder.scarlet:scarlet-core:0.1.9)
... bunch of other duplicates
```

Installing only one or the other results in missing packages.

How do I install the plugin without having a bunch of duplicate symbols?

**Comment by aaronhe42** [comment]
it looks like you have `com.github.tinder.scarlet:scarlet-core:0.1.9` declared somewhere in your dependencies

**Comment by whoyawn** [comment]
Those two are the only ones I have. Could this be an issue with the websocket dependency also installing core again?

**Comment by rogerthat94** [comment]
I had the same issue. I fixed it by switching to 0.1.17

**Comment by whoyawn** [comment]
Installing 0.2.4 for both also did the trick for me.

**Comment by rogerthat94** [comment]
They said 0.1.x is the production version, so 0.1.17 seemed like a better option.

**Comment by aaronhe42** [comment]
I'm not able to reproduce this. can you provide a sample project?

**Comment by joelromanpr** [comment]
You can prevent this by taking your root build gradle file and declaring the dependencies in it and then just calling `implementation libs.dependency` that way you are always sure you are not only not duplicating but also having consistent versions across. In the end gradle is smart enough to resolve its graph and you should not have issues ;)

**Comment by rogerthat94** [comment]
> I'm not able to reproduce this. can you provide a sample project?

https://github.com/rogerthat94/ScarletError

I get the error when I try building this.

**Comment by rogerthat94** [comment]
It looks like I run into the error if I use Scarlet 0.1.9 from Jitpack. But it works fine with Scarlet 0.1.9 from JCenter.

**Comment by aaronhe42** [comment]
Scarlet 0.1.8+ are available only in maven central, and the group id is now `com.tinder` instead of `com.github.tinder`

**Comment by mladen1nf** [comment]
You should use:

`  
implementation 'com.tinder.scarlet:scarlet:0.1.9'
implementation "com.tinder.scarlet:websocket-okhttp:0.1.9"
`
without `scarlet-` prefix
